language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install -y g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
